[package]
name = "cell-war"
version = "0.1.0"
edition = "2021"
resolver = "2"

[[bin]]
name = "cell-war"
path = "src/main.rs"

[lib]
name = "cell_war"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
bevy = {version = "0.16", default-features = false, features=['bevy_render', 'bevy_sprite', 'bevy_audio', 'bevy_ui', 'bevy_core_pipeline', 'bevy_asset', 'bevy_winit', 'bevy_scene', 'mp3', 'default_font']}
wasm-bindgen = "0.2"
rand = "0.10.0"
getrandom = { version = "=0.2.17", features = ["js"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "=0.2.17", features = ["js"] }

